### ISSUE TITLE
API Back nya sudah masuk production.

### ISSUE THREAD

**Issue by novalramdhani** [infinitedim/12-TKJ_1#11]
Btw, gw pertama kali buka isu di sini, jadi lu bisa akses random api nya di ini link:

[Cek sini](https://random-students.herokuapp.com/api/v1/students)

nanti gw sekalian bikin pull request buat revisi pada file `api.config.js` dan rename file RandomUserApi ke RandomStudentApi.

di random api itu isinya data dummy, karna kelamaan nunggunya gw.

Jadi gimana kak @andrianfaa? Gpp kan rubah dikit kodenya.

**Comment by andrianfaa** [comment]
> Btw, gw pertama kali buka isu di sini, jadi lu bisa akses random api nya di ini link:
> 
> [Cek sini](https://random-students.herokuapp.com/api/v1/students)
> 
> nanti gw sekalian bikin pull request buat revisi pada file `api.config.js` dan rename file RandomUserApi ke RandomStudentApi.
> 
> di random api itu isinya data dummy, karna kelamaan nunggunya gw.
> 
> Jadi gimana kak @andrianfaa? Gpp kan rubah dikit kodenya.

Yoiii gpp ubah aja val, btw api nya dah jadi kah??

**Comment by novalramdhani** [comment]
> > Btw, gw pertama kali buka isu di sini, jadi lu bisa akses random api nya di ini link:
> > [Cek sini](https://random-students.herokuapp.com/api/v1/students)
> > nanti gw sekalian bikin pull request buat revisi pada file `api.config.js` dan rename file RandomUserApi ke RandomStudentApi.
> > di random api itu isinya data dummy, karna kelamaan nunggunya gw.
> > Jadi gimana kak @andrianfaa? Gpp kan rubah dikit kodenya.
> 
> Yoiii gpp ubah aja val, btw api nya dah jadi kah??

Udh kak, klik aja link nya yang gw tulisan warna biru, data nya pake data dummy sih, kelamaan temen kelas isinya jadi males nunggunya hehehe
